# Generated by Django 5.0.6 on 2024-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacina',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
