# Generated by Django 5.0.6 on 2024-07-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remedio_quantidade_vacina_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.remedio')),
            ],
        ),
    ]
