# Generated by Django 4.2.6 on 2024-08-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='responsavel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
