# Generated by Django 5.0.6 on 2024-07-17 18:12

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_completo', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=8)),
                ('cpf', models.IntegerField(max_length=14, unique=True)),
                ('rg', models.IntegerField(max_length=15, unique=True)),
                ('nome_mae', models.CharField(max_length=50)),
                ('nome_pai', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.pessoa')),
                ('num_cartao_sus', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.pessoa')),
                ('num_conselho', models.CharField(max_length=20)),
                ('profissao', models.CharField(choices=[('ENF', 'Enfermeiro(a)'), ('MED', 'Médico(a)'), ('TEC_ENF', 'Tecnólogo em Enfermagem(a)'), ('DENT', 'Dentista'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('ACS', 'Agente Comunitário de Saúde'), ('PSICOLOGO', 'Psicólogo(a)'), ('NUTRICIONISTA', 'Nutricionista')], max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
