# Generated by Django 5.0.6 on 2024-07-21 17:08

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nome_completo', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, validators=[usuarios.models.validate_numeric])),
                ('rg', models.CharField(max_length=15, validators=[usuarios.models.validate_numeric])),
                ('nome_mae', models.CharField(max_length=50)),
                ('nome_pai', models.CharField(max_length=50)),
                ('num_cartao_sus', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('nome_completo', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, validators=[usuarios.models.validate_numeric])),
                ('rg', models.CharField(max_length=15, validators=[usuarios.models.validate_numeric])),
                ('nome_mae', models.CharField(max_length=50)),
                ('nome_pai', models.CharField(max_length=50)),
                ('num_conselho', models.CharField(max_length=20)),
                ('profissao', models.CharField(choices=[('ENF', 'Enfermeiro(a)'), ('MED', 'Médico(a)'), ('TEC_ENF', 'Tecnólogo em Enfermagem'), ('DENT', 'Dentista'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('ACS', 'Agente Comunitário de Saúde'), ('PSICOLOGO', 'Psicólogo(a)'), ('NUTRICIONISTA', 'Nutricionista')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
