# Generated by Django 4.2.6 on 2024-08-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
