# Generated by Django 4.2.6 on 2024-08-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimento', '0001_initial'),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios_estabelecimento', to='estabelecimento.estabelecimento'),
        ),
    ]
