# Generated by Django 5.0.6 on 2024-07-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('usuarios', '0002_alter_paciente_options_alter_profissional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'is_paciente': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_como_paciente', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(limit_choices_to={'is_profissional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_como_profissional', to='usuarios.usuario'),
        ),
    ]
