# Generated by Django 5.0.6 on 2024-07-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_paciente_alter_consulta_profissional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='observacoes',
            new_name='status',
        ),
    ]
