# Generated by Django 5.0.6 on 2024-07-27 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_rename_observacoes_consulta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='data_consulta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.TextField(default='pendente'),
            preserve_default=False,
        ),
    ]
