# Generated by Django 5.0.6 on 2024-07-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_consulta_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='profissional',
        ),
    ]
